### ISSUE TITLE
classes are lost when used on a router-link component

### ISSUE THREAD

**Issue by davestaab** [mlturner88/vue-simple-bem#3]
I'm using `v-bem` on a `router-link` component from the Vue Router. 
```vue
<router-link v-bem:link to="/demo">Top</router-link>
```

When the link is clicked, the `v-bem` class disappears. It's because router link is also adding/removing classes. 

Maybe we can tie into other directive lifecycle hooks to keep the DOM classes in sync.

**Comment by Aaron-Pool** [comment]
Actually, I'm guessing this is the same bug I spoke about a few months back.

You can see Evan's response here: https://github.com/vuejs/vue/issues/9216

He didn't respond to my question about if there was a way to achieve similar behavior, of course, because that would have been too easy.

It would probably be pretty performant to cache the calculated bem classes on the components whenever they're added, and then add a [Mutation Observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver) to readd them in the event that the classes are lost.

**Comment by mlturner88** [comment]
This is fixed in [v1.2.0](https://github.com/mlturner88/vue-simple-bem/releases/tag/v1.2.0)
